import type { TableName } from "../types";

/**
 * Coloanele trimise spre Supabase, tabel cu tabel.
 *
 * PostgREST refuză un `upsert` în lot dacă rândurile nu au exact aceleași
 * chei, iar rândurile locale pot diferi (unele vin din backup, altele au
 * câmpuri opționale lipsă). Normalizăm totul după lista de mai jos — care
 * este și filtrul pentru coloanele puse de server (`synced_at`).
 */

const BASE = ["id", "user_id", "created_at", "updated_at", "deleted_at"] as const;

export const TABLE_COLUMNS: Record<TableName, readonly string[]> = {
  clients: [
    ...BASE,
    "name",
    "phone",
    "email",
    "address",
    "notes",
    "source",
    "referred_by_client_id",
    "price_adjust",
  ],
  projects: [...BASE, "name", "client_id", "address", "notes"],
  jobs: [
    ...BASE,
    "client_id",
    "project_id",
    "title",
    "type",
    "status",
    "address",
    "scheduled_date",
    "scheduled_time",
    "estimated_hours",
    "price_total",
    "material_cost",
    "start_date",
    "end_date",
    "notes",
    "archived_at",
    "in_portfolio",
    "portfolio_description",
    "warranty_of_job_id",
    "material_delivered_at",
    "travel_km",
  ],
  job_measurements: [...BASE, "job_id", "client_id", "kind", "label", "data", "notes"],
  job_photos: [
    ...BASE,
    "job_id",
    "measurement_id",
    "stage",
    "storage_path",
    "local_key",
    "caption",
  ],
  job_materials: [
    ...BASE,
    "job_id",
    "material_id",
    "name",
    "quantity",
    "unit",
    "unit_price",
    "purchased",
    "taken_from_stock",
    "returned_quantity",
  ],
  materials: [
    ...BASE,
    "name",
    "category",
    "quantity",
    "unit",
    "price",
    "supplier",
    "notes",
    "pack_size",
  ],
  payments: [...BASE, "job_id", "client_id", "amount", "kind", "method", "paid_at", "note"],
  expenses: [
    ...BASE,
    "job_id",
    "category",
    "amount",
    "spent_at",
    "note",
    "receipt_path",
    "receipt_local_key",
    "member_id",
  ],
  quotes: [
    ...BASE,
    "number",
    "client_id",
    "job_id",
    "status",
    "title",
    "advance",
    "discount",
    "valid_until",
    "notes",
    "sent_at",
    "accepted_at",
    "public_token",
    "accepted_by_client_at",
    "client_signature",
    "client_signature_image",
    "reminder_sent_at",
  ],
  quote_items: [...BASE, "quote_id", "description", "quantity", "unit", "unit_price", "position"],
  invoices: [
    ...BASE,
    "job_id",
    "client_id",
    "series",
    "number",
    "issued_at",
    "due_at",
    "client_name",
    "client_address",
    "client_phone",
    "subtotal",
    "vat_percent",
    "tax_percent",
    "language",
    "total",
    "paid_at",
    "notes",
  ],
  tools: [
    ...BASE,
    "name",
    "brand",
    "model",
    "price",
    "purchased_at",
    "warranty_months",
    "notes",
    "photo_path",
    "photo_local_key",
    "job_types",
  ],
  work_sessions: [...BASE, "job_id", "started_at", "ended_at", "duration_minutes", "note"],
  day_blocks: [...BASE, "day", "reason"],
  notifications: [...BASE, "kind", "title", "body", "job_id", "due_date", "read_at"],
  job_tasks: [...BASE, "job_id", "title", "done", "done_at", "position"],
  fixed_costs: [...BASE, "name", "amount", "started_at", "ended_at", "notes"],
  installments: [
    ...BASE,
    "job_id",
    "label",
    "amount",
    "due_date",
    "payment_id",
    "position",
  ],
  handovers: [
    ...BASE,
    "job_id",
    "client_id",
    "number",
    "handed_at",
    "client_name",
    "client_address",
    "client_phone",
    "work_summary",
    "warranty_months",
    "notes",
    "signature",
    "signer_name",
    "signed_at",
    "public_token",
  ],
  settings: [
    ...BASE,
    "full_name",
    "phone",
    "email",
    "company",
    "logo_path",
    "logo_local_key",
    "currency",
    "units",
    "default_rates",
    "price_list",
    "task_templates",
    "expense_categories",
    "material_categories",
    "notification_prefs",
    "vat_percent",
    // `tax_percent` și `language` existau în baza de date, dar lipseau de aici,
    // deci nu plecau niciodată spre server: schimbai limba pe un telefon și pe
    // celălalt rămânea cum era. Lista asta e singurul filtru la trimitere.
    "tax_percent",
    "language",
    "quote_terms",
    "photo_stamp",
    "acclimatization_hours",
    "stair_limits",
    "member_rates",
    "portfolio_token",
    "portfolio_intro",
    "calendar_token",
  ],
};

/** Aduce rândul la forma exactă pe care o așteaptă tabelul. */
export function toPayload(table: TableName, row: Record<string, unknown>) {
  const payload: Record<string, unknown> = {};
  for (const column of TABLE_COLUMNS[table]) {
    payload[column] = row[column] ?? null;
  }
  return payload;
}
